services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - .:/app
